name: Build Android APK

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
env:
  JAVA_VERSION: 19
jobs:
  build-test:
    uses: ./.github/workflows/build_test.yml
  apk:
    runs-on: ubuntu-latest
    environment: apk-release
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ env.JAVA_VERSION }}
          # noinspection YAMLIncompatibleTypes
          cache: 'gradle'
      - name: Save the keystore
        env:
          BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
        run: |
          echo $BASE64_KEYSTORE | base64 --decode > keystore.jks
      - name: Create local.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "# from github action" >> android/local.properties
          echo "release.store.password=$KEYSTORE_PASSWORD" >> android/local.properties
          echo "release.key.password=$KEYSTORE_PASSWORD" >> android/local.properties
          echo "release.key.alias=appsign" >> android/local.properties
          echo "release.store.file=$GITHUB_WORKSPACE/keystore.jks" >> android/local.properties
      - name: Build APK
        run: flutter build apk --dart-define GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}} --release -v --build-number ${{github.run_number}}
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: google_search_diff-release
          path: build/app/outputs/flutter-apk/app-release.apk
