name: Build project for different environments

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: ./.github/workflows/part_build_test.yml
  apk:
    uses: ./.github/workflows/part_apk_release.yml
    secrets: inherit
    needs: build-test
  ipa:
    uses: ./.github/workflows/part_ios_release.yml
    secrets: inherit
    needs: build-test
