name: Build for Android (Appbundle)

on:
  workflow_call:
    secrets:
      BASE64_SERVICE_ACCOUNT_JSON:
        required: true
        description: The keystore for signing the build
      KEYSTORE_PASSWORD:
        required: true
        description: Password to unlock the keystore

env:
  SERVICE_ACCOUNT_PATH: service_account.json

jobs:
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    environment: appbundle-release
    steps:
      - name: 🫲 Download working directory
        uses: actions/download-artifact@v4
        with:
          name: working-directory
      - name: 🫲 Download Appbundle
        uses: actions/download-artifact@v4
        with:
          name: appbundle-release
      - name: Service Account JSON
        id: service-account
        run: echo "json=$(echo $BASE64_SERVICE_ACCOUNT_JSON | base64 --decode | tr -d '\n')" >> "$GITHUB_OUTPUT"
        env:
          BASE64_SERVICE_ACCOUNT_JSON: ${{ secrets.BASE64_SERVICE_ACCOUNT_JSON}}
      - name: Service Account File
        env:
          SERVICE_ACCOUNT_JSON: ${{ steps.service-account.outputs.json }}
          SERVICE_ACCOUNT_PATH: ${{ env.SERVICE_ACCOUNT_PATH }}
        run: |
          echo $SERVICE_ACCOUNT_JSON > $SERVICE_ACCOUNT_PATH
      - name: Get package name
        id: package
        run: echo "name=$(grep applicationId android/app/build.gradle|cut -d'"' -f2)" >> "$GITHUB_OUTPUT"
        # https://medium.com/lodgify-technology-blog/deploy-your-flutter-app-to-google-play-with-github-actions-f13a11c4492e
      - name: Deploy to Play Store (Internal testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ env.SERVICE_ACCOUNT_PATH }}
          packageName: ${{ steps.package.outputs.name }}
          releaseFiles: outputs/bundle/release/app-release.aab
          track: internal
          mappingFile: outputs/mapping/release/mapping.txt
          debugSymbols: intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/
      - name: Promote release
        uses: kevin-david/promote-play-release@v1.1.0
        with:
          service-account-json-raw: ${{ steps.service-account.outputs.json }}
          package-name: ${{ steps.package.outputs.name }}
          from-track: internal
          to-track: beta
