name: Create Release Version

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  pages: write
  id-token: write

env:
  JAVA_VERSION: 19

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: ./.github/workflows/part_build_test.yml
  apk:
    uses: ./.github/workflows/part_apk_release.yml
    secrets: inherit
    needs: build-test
  release-to-github:
    runs-on: ubuntu-latest
    needs: apk
    steps:
      - name: 🫲 Download APK
        uses: actions/download-artifact@v4
        with:
          name: apk-release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-release.apk
          generate_release_notes: true
          fail_on_unmatched_files: true

  appbundle:
    uses: ./.github/workflows/part_appbundle_release.yml
    secrets: inherit
    needs: build-test
  release-to-appstore-internal:
    uses: ./.github/workflows/part_deploy_playstore.yml
    needs: appbundle
    secrets: inherit

  ios:
    uses: ./.github/workflows/part_ios_release.yml
    secrets: inherit
    needs: build-test
